services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $debug: '%kernel.debug%'

    Softspring\CmsBundle\EventListener\WelcomePageListener: ~